### ISSUE TITLE
`broker providers` doesn't let one select an AT instance

### ISSUE THREAD

**Issue by Ichimonji10** [SatelliteQE/broker#127] opened 2021-08-06 20:39 UTC
I'm unable to select an AT instance when examining provider inventories:

```console
$ broker providers AnsibleTower --inventories
[INFO 210806 16:34:19] Querying provider AnsibleTower
[INFO 210806 16:34:19] Using token authentication
[INFO 210806 16:34:20] Available Inventories:
    satlab-iqe-01-openstack
    satlab-rhv-02-inventory
$ broker providers AnsibleTower::mr --inventories
Usage: broker providers [OPTIONS] COMMAND [ARGS]...
Try 'broker providers --help' for help.

Error: No such command 'AnsibleTower::mr'.
```

This behavior is limiting because different AT instances can, in fact, have different inventories. This example comes from a case where the AT instance spun up for the duration of a merge request (`AnsibleTower::mr`) has a different inventory (`satlab-iqe-01-inventory`) than the default production AT instance.

**Comment by JacobCallahan** [comment] 2021-08-06 21:04
This is currently a limitation of the subcommand generation process. One solution to this would be to add additional provider entries for each instance defined in the config. This could look something like this

```
$  broker providers --help                                                                                                 
Usage: broker providers [OPTIONS] COMMAND [ARGS]...

  Get information about a provider and its actions

Options:
  --help  Show this message and exit.

Commands:
  AnsibleTower  Get information about a provider's actions
  AnsibleTower::inst2  Get information about a provider's actions
  ```

Note how there are actually two instances represented here. The default and `inst2`. The instance that is default will benefit from the shorter notation. However, additional instances will be listed as another subcommand option.

**Comment by ogajduse** [comment] 2021-08-10 09:27
This issue looks like a duplicate of #115

**Comment by JacobCallahan** [comment] 2021-08-10 11:05
> This issue looks like a duplicate of #115 

Ahh it sure is!

**Closed** 2023-03-31 01:02 UTC
Labels: enhancement
