### ISSUE TITLE
`BrokerError: getattr(): attribute name must be string` during checkout

### ISSUE THREAD

**Issue by ogajduse** [SatelliteQE/broker#136] opened 2021-09-09 08:47 UTC
Reproducer:
```
$ broker checkout --workflow deploy-base-rhel --template tpl-cmp-RHEL-8.5.0-20210816.n.0
[INFO 210909 10:24:01] Using provider AnsibleTower to checkout
[INFO 210909 10:24:01] Using token authentication
[INFO 210909 10:24:03] No inventory specified, Ansible Tower will use a default.
[INFO 210909 10:24:04] Waiting for job: 
    API: https://infra-ansible-tower-01.infra.ourdomain.com/api/v2/workflow_jobs/1074415/
    UI: https://infra-ansible-tower-01.infra.ourdomain.com/#/workflows/1074415
[INFO 210909 10:28:46] Host: dhcp-3-245.vms.ourdomain.com
[INFO 210909 10:28:46] Using provider AnsibleTower to checkout
[INFO 210909 10:28:47] Using token authentication
[ERROR 210909 10:28:48] BrokerError: getattr(): attribute name must be string
```

Broker is reaching out to Tower after the `deploy-base-rhel` WF was successful and then fails with BrokerError.
This reproducer should work with

Broker version:
```
$ broker --version
Version: 0.1.22
```

My broker config:
```yaml
# Broker settings
debug: True
inventory_file: "inventory.yaml"
# Host Settings
host_username: "root"
host_password: ""

# Provider settings
AnsibleTower:
  instances:
    - rhv:
        base_url: "https://infra-ansible-tower-01.infra.ourdomain.com/"
        # username: "ogajduse"
        # password: ""
        token: mytoken
        default: True
    - osp:
        base_url: "https://infra-ansible-tower-01.infra.ourdomain.com/"
        # username: "ogajduse"
        # password: ""
        token: EknRl0veErGgQjS8CA83KkoJyD1r1n
        inventory: "satlab-osp-01-inventory"
    - testing:
        base_url: "https://dhcp-2-80.vms.ourdomain.com/"
        inventory: "satlab-rhv-02-inventory"
        username: ogajduse
        password: ""
        #default: True
  release_workflow: "remove-vm"
  extend_workflow: "extend-vm"
  workflow_timeout: 3600
  #results_limit: 50
```

**Comment by ogajduse** [comment] 2021-09-09 08:48
Usage of the `--template` argument was discussed with @rdrazny and we did not found out why it failed.

**Comment by JacobCallahan** [comment] 2021-09-28 18:21
closing as duplicate of #124

**Closed by JacobCallahan** 2021-09-28 18:21 UTC
